duplicate -y :sounds:BAREXP.AIFF :Game3DO:Remote:Sounds:Sound60.AIFF 
duplicate -y :sounds:BFG.AIFF :Game3DO:Remote:Sounds:Sound05.AIFF 
duplicate -y :sounds:BGACT.AIFF :Game3DO:Remote:Sounds:Sound57.AIFF
duplicate -y :sounds:BGDTH1.AIFF :Game3DO:Remote:Sounds:Sound48.AIFF
duplicate -y :sounds:BGDTH2.AIFF :Game3DO:Remote:Sounds:Sound49.AIFF
duplicate -y :sounds:BGSIT1.AIFF :Game3DO:Remote:Sounds:Sound34.AIFF
duplicate -y :sounds:BGSIT2.AIFF :Game3DO:Remote:Sounds:Sound35.AIFF
duplicate -y :sounds:BRSDTH.AIFF :Game3DO:Remote:Sounds:Sound53.AIFF
duplicate -y :sounds:BRSSIT.AIFF :Game3DO:Remote:Sounds:Sound38.AIFF
duplicate -y :sounds:CACDTH.AIFF :Game3DO:Remote:Sounds:Sound51.AIFF
duplicate -y :sounds:CACSIT.AIFF :Game3DO:Remote:Sounds:Sound37.AIFF
duplicate -y :sounds:CLAW.AIFF :Game3DO:Remote:Sounds:Sound43.AIFF
duplicate -y :sounds:DMACT.AIFF :Game3DO:Remote:Sounds:Sound58.AIFF
duplicate -y :sounds:DMPAIN.AIFF :Game3DO:Remote:Sounds:Sound24.AIFF
duplicate -y :sounds:DORCLS.AIFF :Game3DO:Remote:Sounds:Sound19.AIFF
duplicate -y :sounds:DOROPN.AIFF :Game3DO:Remote:Sounds:Sound18.AIFF
duplicate -y :sounds:FIRSHT.AIFF :Game3DO:Remote:Sounds:Sound13.AIFF
duplicate -y :sounds:FIRXPL.AIFF :Game3DO:Remote:Sounds:Sound15.AIFF
duplicate -y :sounds:ITEMUP.AIFF :Game3DO:Remote:Sounds:Sound27.AIFF
duplicate -y :sounds:ITMBK.AIFF :Game3DO:Remote:Sounds:Sound64.AIFF
duplicate -y :sounds:NOWAY.AIFF :Game3DO:Remote:Sounds:Sound59.AIFF
duplicate -y :sounds:OOF.AIFF :Game3DO:Remote:Sounds:Sound29.AIFF
duplicate -y :sounds:PISTOL.AIFF :Game3DO:Remote:Sounds:Sound01.AIFF
duplicate -y :sounds:PLASMA.AIFF :Game3DO:Remote:Sounds:Sound04.AIFF
duplicate -y :sounds:PLDETH.AIFF :Game3DO:Remote:Sounds:Sound44.AIFF
duplicate -y :sounds:PLPAIN.AIFF :Game3DO:Remote:Sounds:Sound23.AIFF
duplicate -y :sounds:PODTH1.AIFF :Game3DO:Remote:Sounds:Sound45.AIFF
duplicate -y :sounds:PODTH2.AIFF :Game3DO:Remote:Sounds:Sound46.AIFF
duplicate -y :sounds:POPAIN.AIFF :Game3DO:Remote:Sounds:Sound25.AIFF
duplicate -y :sounds:POSACT.AIFF :Game3DO:Remote:Sounds:Sound56.AIFF
duplicate -y :sounds:POSIT1.AIFF :Game3DO:Remote:Sounds:Sound31.AIFF
duplicate -y :sounds:POSIT2.AIFF :Game3DO:Remote:Sounds:Sound32.AIFF
duplicate -y :sounds:PSTART.AIFF :Game3DO:Remote:Sounds:Sound16.AIFF
duplicate -y :sounds:PSTOP.AIFF :Game3DO:Remote:Sounds:Sound17.AIFF
duplicate -y :sounds:PUNCH.AIFF :Game3DO:Remote:Sounds:Sound61.AIFF
duplicate -y :sounds:RLAUNC.AIFF :Game3DO:Remote:Sounds:Sound10.AIFF
duplicate -y :sounds:RXPLOD.AIFF :Game3DO:Remote:Sounds:Sound12.AIFF
duplicate -y :sounds:SAWFUL.AIFF :Game3DO:Remote:Sounds:Sound08.AIFF
duplicate -y :sounds:SAWHIT.AIFF :Game3DO:Remote:Sounds:Sound09.AIFF
duplicate -y :sounds:SAWIDL.AIFF :Game3DO:Remote:Sounds:Sound07.AIFF
duplicate -y :sounds:SAWUP.AIFF :Game3DO:Remote:Sounds:Sound06.AIFF
duplicate -y :sounds:SGCOCK.AIFF :Game3DO:Remote:Sounds:Sound03.AIFF
duplicate -y :sounds:SGTATK.AIFF :Game3DO:Remote:Sounds:Sound42.AIFF
duplicate -y :sounds:SGTDTH.AIFF :Game3DO:Remote:Sounds:Sound50.AIFF
duplicate -y :sounds:SGTSIT.AIFF :Game3DO:Remote:Sounds:Sound36.AIFF
duplicate -y :sounds:SHOTGN.AIFF :Game3DO:Remote:Sounds:Sound02.AIFF
duplicate -y :sounds:SKLATK.AIFF :Game3DO:Remote:Sounds:Sound41.AIFF
duplicate -y :sounds:SKLDTH.AIFF :Game3DO:Remote:Sounds:Sound52.AIFF
duplicate -y :sounds:SLOP.AIFF :Game3DO:Remote:Sounds:Sound26.AIFF
duplicate -y :sounds:STNMOV.AIFF :Game3DO:Remote:Sounds:Sound20.AIFF
duplicate -y :sounds:SWTCHN.AIFF :Game3DO:Remote:Sounds:Sound21.AIFF
duplicate -y :sounds:SWTCHX.AIFF :Game3DO:Remote:Sounds:Sound22.AIFF
duplicate -y :sounds:TELEPT.AIFF :Game3DO:Remote:Sounds:Sound30.AIFF
duplicate -y :sounds:WPNUP.AIFF :Game3DO:Remote:Sounds:Sound28.AIFF
 